//get all Students
GET http://localhost:3000/api/students

###

//post new Student
POST http://localhost:3000/api/students
Content-Type: application/json

{
  "firstName": "Bojan",
  "lastName": "Marković",
  "indexNumber": "01-2019",
  "email": "boj.markovic@hotmail.com",
  "phone": "+387 65 999 999"
}

###

//get unique Student
GET http://localhost:3000/api/student/62f6096c8e86e00bffb69a8d

###

//delete Student
DELETE http://localhost:3000/api/student/62f77aa62f4b43d79065ba82

###

//edit student
PATCH http://localhost:3000/api/student/62f77b7f487227a9f4db5b60
Content-Type: application/json

{
  "firstName": "Marija",
  "email": "marina.blagic@hotmail.com",
  "phone": "+387 65 331 159",
  "gradeHistory": [
    {
      "grade": 9,
      "dateExam": "09.09.2018",
      "subject": "Introduction to Civil Engineering"
    },
    {
      "grade": 10,
      "dateExam": "10.10.2018",
      "subject": "Statics and Mechanics of Solids"
    }
  ]
}

