//GET all Students
GET https://students-app-server-plum.vercel.app/api/students

###

//POST new Student
POST https://students-app-server-plum.vercel.app/api/students
Content-Type: application/json

{
  "firstName": "Michael",
  "lastName": "Rondo",
  "indexNumber": "10-2010",
  "email": "boj.markovic@hotmail.com",
  "phone": "+387 65 999 999"
}

###

//GET unique Student
GET https://students-app-server-plum.vercel.app/api/student/34-1999

###

//DELETE Student
DELETE https://students-app-server-plum.vercel.app/api/student/34-1999

###

//EDIT Student
PATCH https://students-app-server-plum.vercel.app/api/student/34-1999
Content-Type: application/json

{
  "firstName": "Marija",
  "email": "marina.blagic@hotmail.com",
  "phone": "+387 65 331 159",
  "gradeHistory": [
    {
      "grade": 9,
      "dateExam": "09.09.2018",
      "subject": "Introduction to Civil Engineering"
    },
    {
      "grade": 10,
      "dateExam": "10.10.2018",
      "subject": "Statics and Mechanics of Solids"
    }
  ]
}

###

//QUERING Students
GET https://students-app-server-plum.vercel.app/api/studentsq=mar

###

//  REGISTER and LOGIN  //

###

//REGISTER user
POST http://localhost:4000/api/register
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "test"
}

###

//LOGIN user
POST http://localhost:4000/api/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "test"
}

